"""DMP package."""

from .schema_io import (
    DEFAULT_DMP_PATH,
    DK_UNI_MAP,
    EXTRA_ENUMS,
    LICENSE_LINKS,
    SCHEMA_URLS,
    SCHEMA_VERSION,
    dmp_default_templates,
    load_json,
    save_json,
)
from .normalization_and_templates import (
    data_type_from_path,
    fetch_schema,
    get_repokit_info_payload,
    norm_rel_urlish,
    now_iso_minute,
    set_repokit_info_payload,
    today_iso,
    to_bytes_mb,
    update_cookiecutter_from_dmp,
)
from .workflow_update_cli import (
    create_or_update_dmp_from_schema,
    ensure_dmp_shape,
    ensure_required_by_schema,
    main,
    normalize_datasets_in_place,
    normalize_root_in_place,
    reorder_dmp_keys,
    repair_empty_enums,
)

__all__ = [
    "DEFAULT_DMP_PATH",
    "DK_UNI_MAP",
    "EXTRA_ENUMS",
    "LICENSE_LINKS",
    "SCHEMA_URLS",
    "SCHEMA_VERSION",
    "dmp_default_templates",
    "load_json",
    "save_json",
    "data_type_from_path",
    "fetch_schema",
    "get_repokit_info_payload",
    "norm_rel_urlish",
    "now_iso_minute",
    "set_repokit_info_payload",
    "today_iso",
    "to_bytes_mb",
    "update_cookiecutter_from_dmp",
    "create_or_update_dmp_from_schema",
    "ensure_dmp_shape",
    "ensure_required_by_schema",
    "main",
    "normalize_datasets_in_place",
    "normalize_root_in_place",
    "reorder_dmp_keys",
    "repair_empty_enums",
]
